version: "3.7"

services:
  ospg-forms-flow-web:
    container_name: OSPG-forms-flow-web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FORMFLOW_SOURCE_REPO_BRANCH=${FORMFLOW_SOURCE_REPO_BRANCH}
        - FORMFLOW_SOURCE_REPO_URL=${FORMFLOW_SOURCE_REPO_URL}
        - NODE_ENV=${NODE_ENV}
        - GENERATE_SOURCEMAP=${GENERATE_SOURCEMAP}
        - REACT_APP_CLIENT_ROLE=${REACT_APP_CLIENT_ROLE}
        - REACT_APP_STAFF_REVIEWER_ROLE=${REACT_APP_STAFF_REVIEWER_ROLE}
        - REACT_APP_STAFF_DESIGNER_ROLE=${REACT_APP_STAFF_DESIGNER_ROLE}
        - REACT_APP_CLIENT_ID=${REACT_APP_CLIENT_ID}
        - REACT_APP_STAFF_REVIEWER_ID=${REACT_APP_STAFF_REVIEWER_ID}
        - REACT_APP_STAFF_DESIGNER_ID=${REACT_APP_STAFF_DESIGNER_ID}
        - REACT_APP_USER_RESOURCE_FORM_ID=${REACT_APP_USER_RESOURCE_FORM_ID}
        - REACT_APP_API_SERVER_URL=${REACT_APP_API_SERVER_URL}
        - REACT_APP_API_PROJECT_URL=${REACT_APP_API_PROJECT_URL}
        - REACT_APP_KEYCLOAK_CLIENT=${REACT_APP_KEYCLOAK_CLIENT}
        - REACT_APP_ANONYMOUS_ID=${REACT_APP_ANONYMOUS_ID}
        - REACT_APP_WEB_BASE_URL=${REACT_APP_WEB_BASE_URL}
        - REACT_APP_CAMUNDA_API_URI=${REACT_APP_CAMUNDA_API_URI}
        - REACT_APP_WEBSOCKET_ENCRYPT_KEY=${REACT_APP_WEBSOCKET_ENCRYPT_KEY}
        - REACT_APP_KEYCLOAK_URL_REALM=${REACT_APP_KEYCLOAK_URL_REALM}
        - REACT_APP_KEYCLOAK_URL=${REACT_APP_KEYCLOAK_URL}
        - REACT_APP_APPLICATION_NAME=${REACT_APP_APPLICATION_NAME}
        - REACT_APP_USER_ACCESS_PERMISSIONS=${REACT_APP_USER_ACCESS_PERMISSIONS}
        - REACT_APP_WEB_BASE_CUSTOM_URL=${REACT_APP_WEB_BASE_CUSTOM_URL}
        - REACT_APP_FORMIO_JWT_SECRET=${REACT_APP_FORMIO_JWT_SECRET}
    env_file:
      - ./.env
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3000:8080"
    tty: true
